# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------
# Experiment settings to train/test a small 1 hidden layer Recurrent Neural
# Net on the text of the book Moby Dick.
# This models currently runs on CPU only.

!obj:experiments.FitPredictErrorExperiment {

  metrics: {
    train: [
      !obj:metrics.MisclassPercentage {},
    ],
    test: [
      !obj:metrics.MisclassPercentage {},
    ],
  },

  # Enable predictions to generate example output strings. Requires CPU backend
  predictions: [train, test],

  dataset: &ds !obj:datasets.StockPrice {
    repo_path: '~/data',
    sample_pct: 100, # 10% gives 400 batches like in rnn2
    data_dim: &dd 13,
    unrolls: &ur 50,
    backend_type: &bt np.float32,  # 64 is needed for numerical gradients
  },

  weight_inits: [
    &wt_init !obj:params.SparseEigenValGen {
      sparseness: 15,
      eigenvalue: 1.2,
    },
    &wt_initb !obj:params.NormalValGen {
      loc: 0.0,
      scale: 0.1,
      bias_init: 1.0,
    },
  ],

  lrule: &gdm {
    type: gradient_descent,
    lr_params: {
      learning_rate: 0.001,  # try 0.002 for RNN, 0.2 for LSTM to start with
      momentum_params: {
        type: linear_monotone,
        initial_coef: 0.9,
        saturated_coef: 0.99,
        start_epoch: 10,
        saturate_epoch: 100,
      },
    },
  },

  # simple RNN model specification
  model: !obj:models.RNN {

    num_epochs: 10,
    batch_size: &bs 1,
    reset_period: 100,  # 50 for LSTM, 20 for RNN?
    unrolls: *ur,
    make_plots: True,
    truncate: True,  # truncate the back-propagation through time
    # Note: Numerical gradient checking is only supported with CPU fp64 backend
    backend_type: *bt,
    num_grad_params: {

      name: output,  # For RNN: output, input, rec.
                     # For LSTM: lstm_fx, lstm_ih, lstm_fh, lstm_oh, lstm_ch
      eps: 0.000001, # use 1e-6 and fp64 if possible
      x: 12,
      y: 60,
      z: 63,
      w: 55,
      v: 56,
      u: 15,
    },

    shortcut_deriv: False,
    layers: [
      &datalayer !obj:layers.DataLayer {
        name: datalayer,
        backend_type: *bt,
        nout: *dd,
      },
      !obj:layers.RecurrentHiddenLayer {

        name: recurrent,
        backend_type: *bt,
        lrule_init: *gdm,
        nout: 128,
        unrolls: *ur,
        activation: !obj:transforms.Tanh {},
        #gate_activation: !obj:transforms.Logistic {},
        weight_init: *wt_initb,
        weight_init_rec: *wt_initb,
      },

      &lastlayer !obj:layers.RecurrentOutputLayer {
        name: output,
        backend_type: *bt,
        lrule_init: *gdm,
        nout: *dd,
        unrolls: *ur,
        activation: !obj:transforms.Logistic {},
        brule_init: *gdm,
        weight_init: *wt_initb,
      },

      &costlayer !obj:layers.RecurrentCostLayer {
        name: cost,
        backend_type: *bt,
        ref_layer: *datalayer,
        cost: !obj:transforms.SumSquaredDiffs {
          backend_type: *bt,
        },
      },
    ],
  },

  logging: {
    level: 20,  # 10 debug, 20 info, 30 warning
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
